#!bin/bash
echo " 
Create By Aliza 
T.H.C Team🇮🇷
"
echo " 
                 ##############################
                 #     ☣️  T.H.C Team ⚛️        #
                 #        ☢️  Aliza            #
                 ##############################"
apt-get update
apt-get install play-audio
echo " installed audio player ...√"
play-audio nari.mp3 |telnet towel.blinkenlights.nl|
